const API="https://sportzfylive.svimranmy.workers.dev";
let adminSession=localStorage.getItem("sportzfy_admin_session")||"",allMatches=[],matchPage=1,currentMatch=null,editingStreamIndex=-1;
const $=id=>document.getElementById(id);
const esc=v=>String(v??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#039;");
function toast(msg){const t=$("toast");t.textContent=msg;t.classList.remove("hidden");clearTimeout(window.__toast);window.__toast=setTimeout(()=>t.classList.add("hidden"),2600)}
async function api(path,options={}){const r=await fetch(API+path,{...options,headers:{"Accept":"application/json","Content-Type":"application/json",...(adminSession?{"X-Admin-Session":adminSession}:{}),...(options.headers||{})}});let d=null;try{d=await r.json()}catch(_){}if(!r.ok)throw new Error(d?.error||"HTTP "+r.status);return d}
async function loginAdmin(){const token=$("adminToken").value.trim();if(!token)return;try{const r=await fetch(API+"/api/admin/login",{method:"POST",headers:{"Content-Type":"application/json","X-Admin-Token":token}}),d=await r.json();if(!r.ok)throw new Error(d?.error||"Authentication failed");adminSession=d.session;localStorage.setItem("sportzfy_admin_session",adminSession);$("login").style.display="none";await boot()}catch(e){$("loginError").textContent=e.message||"Authentication failed."}}
async function boot(){await Promise.all([loadMatches(),loadContent()]);renderDashboard()}
function toggleSidebar(){$("sidebar").classList.toggle("open")}
function showPage(page){document.querySelectorAll(".page").forEach(x=>x.classList.add("hidden"));$("page-"+page)?.classList.remove("hidden");document.querySelectorAll(".nav-item").forEach(x=>x.classList.toggle("active",x.dataset.page===page));$("pageTitle").textContent={dashboard:"Dashboard",matches:"Matches",settings:"Website Content",sync:"Sync & Automation"}[page]||"Dashboard";$("sidebar").classList.remove("open");if(page==="dashboard")renderDashboard();if(page==="matches")loadMatches();if(page==="settings"){loadContent();populateFeatured()}}
async function loadMatches(){try{allMatches=await api("/api/admin/matches");if(!Array.isArray(allMatches))allMatches=[];renderMatchList();renderDashboard()}catch(e){if($("allMatches"))$("allMatches").innerHTML='<div class="error">Unable to load matches: '+esc(e.message)+"</div>"}}
function matchStreams(m){return Array.isArray(m?.streams)?m.streams.map((x,i)=>({...x,id:String(x.id||crypto.randomUUID()),name:String(x.name||"Stream "+(i+1)),language:String(x.language||"English"),league:String(x.league||""),quality:String(x.quality||"HD")})):[]}
function matchSources(m){return Array.isArray(m?.sources)?m.sources.map(s=>({source:String(s?.source||""),id:String(s?.id||"")})).filter(s=>s.source&&s.id):[]}
function sourceSummary(m){const s=matchSources(m);return s.length?s.map(x=>x.source).join(", "):"No Streamed sources"}
function teamName(v){if(typeof v==="string")return v;if(v&&typeof v==="object")return String(v.name||v.title||"");return""}
function slugify(v){return String(v||"").trim().toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-+|-+$/g,"")}
function matchUrl(m){return m?.url||"/matches/"+slugify(m?.title||"match")+"-"+String(m?.externalId||m?.id||"").replace(/[^a-zA-Z0-9-]/g,"")}
function renderDashboard(){const now=Date.now();$("statMatches").textContent=allMatches.length;$("statActive").textContent=allMatches.filter(m=>m.status!=="finished").length;$("statLive").textContent=allMatches.filter(m=>m.status==="live").length;$("statStreams").textContent=allMatches.reduce((n,m)=>n+matchStreams(m).length,0);const saved=localStorage.getItem("sportzfy_admin_last_fetch");$("lastFetch").textContent=saved||"No fetch recorded yet.";$("healthLastRun").textContent=saved||"—"}
async function refreshDashboard(){try{await loadMatches();localStorage.setItem("sportzfy_admin_last_fetch",new Date().toLocaleString("en-GB",{hour12:true}));renderDashboard();toast("Dashboard refreshed")}catch(e){$("recentErrors").textContent="1";toast(e.message)}}
async function runMaintenance(){try{$("lastFetchStatus").textContent="Running…";await api("/api/admin/sync-streamed",{method:"POST"});await loadMatches();localStorage.setItem("sportzfy_admin_last_fetch",new Date().toLocaleString("en-GB",{hour12:true}));$("lastFetchStatus").textContent="Healthy";renderDashboard();toast("Fetch & maintenance complete")}catch(e){$("lastFetchStatus").textContent="Error";$("recentErrors").textContent="1";toast(e.message)}}
function renderMatchList(){const q=($("matchSearch")?.value||"").toLowerCase().trim(),filtered=allMatches.filter(m=>[m.title,m.category,m.status,teamName(m.teams?.home),teamName(m.teams?.away)].some(v=>String(v||"").toLowerCase().includes(q))),size=Number($("matchPageSize")?.value||10),pages=Math.max(1,Math.ceil(filtered.length/size));matchPage=Math.min(matchPage,pages);const items=filtered.slice((matchPage-1)*size,matchPage*size);$("allMatches").innerHTML=items.length?items.map(m=>'<div class="row"><div><div class="row-title">'+esc(m.title||"Untitled")+'</div><div class="row-meta">'+esc(m.category||"OTHER")+" · "+esc(m.status||"scheduled")+" · "+esc(m.startTime?new Date(m.startTime).toLocaleString():"No date")+'</div></div><div class="row-meta">Sources: '+esc(sourceText)+'</div><div class="actions"><button class="btn small secondary" onclick="openMatchEditor(\''+esc(m.id)+'\')">Edit</button><button class="btn small danger" onclick="deleteMatch(\''+esc(m.id)+'\')">Delete</button></div></div>').join(""):'<div class="note">No matches found.</div>';renderPagination(pages)}
function renderPagination(pages){const p=$("pagination");p.innerHTML="";const add=(label,n,disabled,active)=>{const b=document.createElement("button");b.textContent=label;b.disabled=disabled;if(active)b.classList.add("active");b.onclick=()=>{matchPage=n;renderMatchList()};p.appendChild(b)};add("First",1,matchPage===1);add("Previous",Math.max(1,matchPage-1),matchPage===1);const start=Math.max(1,Math.min(matchPage-2,pages-4));for(let n=start;n<=Math.min(pages,start+4);n++)add(String(n),n,false,n===matchPage);add("Next",Math.min(pages,matchPage+1),matchPage===pages);add("Last",pages,matchPage===pages)}
function openNewMatch(){currentMatch={id:"",title:"",category:"FOOTBALL",status:"scheduled",startTime:"",poster:"",description:"",teams:{home:"",away:""},competition:"",liveWindow:210,url:"",streams:[]};fillEditor();$("matchesList").classList.add("hidden");$("matchEditor").classList.remove("hidden")}
function openMatchEditor(id){const m=allMatches.find(x=>String(x.id)===String(id));if(!m)return;currentMatch=JSON.parse(JSON.stringify(m));fillEditor();$("matchesList").classList.add("hidden");$("matchEditor").classList.remove("hidden")}
function closeMatchEditor(){currentMatch=null;$("matchEditor").classList.add("hidden");$("matchesList").classList.remove("hidden");renderMatchList()}
function fillEditor(){const m=currentMatch||{};const d=m.startTime?new Date(m.startTime):null;$("editorTitle").textContent=m.id?"Edit Match":"Add Match";$("editDate").value=d&&!isNaN(d)?d.toISOString().slice(0,10):"";$("editTime").value=d&&!isNaN(d)?d.toISOString().slice(11,16):"";$("editCompetition").value=m.competition||m.league||"";$("editSport").value=m.category||"OTHER";$("editHome").value=teamName(m.teams?.home)||m.home||"";$("editAway").value=teamName(m.teams?.away)||m.away||"";$("editStatus").value=m.status||"scheduled";$("editLiveWindow").value=m.liveWindow??210;$("editPoster").value=m.poster||"";$("editUrl").value=matchUrl(m);$("editDescription").value=m.description||"";renderStreams()}
function focusEditor(){$("editDate").focus()}
function composeStart(){const date=$("editDate").value,time=$("editTime").value||"00:00";return date?new Date(date+"T"+time).toISOString():""}
async function saveCurrentMatch(){const old=currentMatch||{},home=$("editHome").value.trim(),away=$("editAway").value.trim(),title=(home&&away)?home+" vs "+away:String(old.title||"Untitled match"),streams=matchStreams({...old,streams:old.streams||[]}),body={title,category:$("editSport").value,startTime:composeStart(),status:$("editStatus").value,poster:$("editPoster").value.trim(),description:$("editDescription").value.trim(),competition:$("editCompetition").value.trim(),home,away,teams:{home,away},liveWindow:Number($("editLiveWindow").value||210),url:$("editUrl").value.trim(),streams};$("editorStatus").textContent="Saving…";try{const r=await api(old.id?"/api/admin/matches/"+encodeURIComponent(old.id):"/api/admin/matches",{method:old.id?"PUT":"POST",body:JSON.stringify(body)});currentMatch=r.match||r;await loadMatches();fillEditor();$("editorStatus").textContent="Saved successfully.";toast("Match saved")}catch(e){$("editorStatus").textContent=e.message}}
function renderStreams(){const list=matchStreams(currentMatch||{});$("streamCount").textContent=list.length;if(currentMatch)currentMatch.streams=list;const b=$("streamsList");if(!list.length){b.innerHTML='<div class="empty">No streams added yet.</div>';return}b.innerHTML=list.map((s,i)=>{const name=s.name||"Stream "+(i+1),meta=[s.language,s.league,s.quality].filter(Boolean).join(" · ");return'<div class="stream-row" draggable="true" data-index="'+i+'" ondragstart="dragStream(event)" ondragover="event.preventDefault()" ondrop="dropStream(event)"><div class="reorder"><button onclick="moveStream('+i+',-1)">⌃</button><button onclick="moveStream('+i+',1)">⌄</button></div><div><span class="stream-name">'+esc(name)+'</span><span class="stream-meta">'+esc(meta)+'</span></div><div class="stream-actions"><button class="text-btn" onclick="copyStream('+i+')">▣</button><button class="text-btn green" onclick="editStream('+i+')">Edit</button><button class="text-btn red" onclick="removeStream('+i+')">Delete</button></div></div>'}).join("")}
function moveStream(i,d){const a=matchStreams(currentMatch),j=i+d;if(j<0||j>=a.length)return;[a[i],a[j]]=[a[j],a[i]];currentMatch.streams=a;renderStreams()}
function dragStream(e){e.dataTransfer.setData("text/plain",e.currentTarget.dataset.index)}
function dropStream(e){const from=Number(e.dataTransfer.getData("text/plain")),to=Number(e.currentTarget.dataset.index);if(Number.isNaN(from)||from===to)return;const a=matchStreams(currentMatch),x=a.splice(from,1)[0];a.splice(to,0,x);currentMatch.streams=a;renderStreams()}
function openStreamModal(index=-1){editingStreamIndex=index;$("streamModalTitle").textContent=index<0?"Add Stream":"Edit Stream";const s=index<0?{name:"",language:"English",league:"",quality:"HD"}:matchStreams(currentMatch)[index];$("streamName").value=s.name||"";$("streamLanguage").value=s.language||"English";$("streamLeague").value=s.league||"";$("streamQuality").value=s.quality||"HD";$("streamModal").classList.add("open")}
function editStream(i){openStreamModal(i)}
function saveStream(){const a=matchStreams(currentMatch),item={id:editingStreamIndex<0?crypto.randomUUID():a[editingStreamIndex].id,name:$("streamName").value.trim()||"Stream "+(editingStreamIndex+1),language:$("streamLanguage").value.trim()||"English",league:$("streamLeague").value.trim(),quality:$("streamQuality").value};if(editingStreamIndex<0)a.push(item);else a[editingStreamIndex]=item;currentMatch.streams=a;renderStreams();closeModal("streamModal")}
function removeStream(i){if(!confirm("Delete this stream?"))return;const a=matchStreams(currentMatch);a.splice(i,1);currentMatch.streams=a;renderStreams()}
function copyStream(i){const s=matchStreams(currentMatch)[i];navigator.clipboard?.writeText(JSON.stringify(s));toast("Stream details copied")}
function closeModal(id){$(id).classList.remove("open")}
async function shareMatch(){const url=$("editUrl").value||matchUrl(currentMatch);try{await navigator.clipboard.writeText(location.origin+url);toast("Match URL copied")}catch(_){toast(url)}}
async function deleteCurrentMatch(){if(!currentMatch?.id)return;if(!confirm("Delete this match?"))return;try{await api("/api/admin/matches/"+encodeURIComponent(currentMatch.id),{method:"DELETE"});closeMatchEditor();await loadMatches();toast("Match deleted")}catch(e){toast(e.message)}}
async function deleteMatch(id){if(!confirm("Delete this match?"))return;try{await api("/api/admin/matches/"+encodeURIComponent(id),{method:"DELETE"});await loadMatches();toast("Match deleted")}catch(e){toast(e.message)}}
function syncStreamed(){try{$("streamedStatus").textContent="Syncing…";const r=await api("/api/admin/sync-streamed",{method:"POST"});$("streamedStatus").textContent="Complete. Streamed "+(r.streamedCount||0)+"; created "+(r.created||0)+"; updated "+(r.updated||0)+"; removed "+(r.removed||0)+".";await loadMatches()}catch(e){$("streamedStatus").textContent=e.message}}
$("matchSearch")?.addEventListener("input",()=>{matchPage=1;renderMatchList()});$("matchPageSize")?.addEventListener("change",()=>{matchPage=1;renderMatchList()});document.querySelectorAll(".nav-item").forEach(x=>x.addEventListener("click",()=>showPage(x.dataset.page)));
if(adminSession){api("/api/admin/matches").then(()=>{$("login").style.display="none";boot()}).catch(()=>{localStorage.removeItem("sportzfy_admin_session");adminSession="";$("login").style.display="grid"})}else $("login").style.display="grid";